name : Setting region in VM
on :
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : "checkout"
        uses: actions/checkout@main
      - name : "VM Credentials"
        with:
        creds: ${{ secrets.VM_CREDENTIALS }} 
      - name: Get XML
        id: getxml
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
        xml-file: 'india.xml'
        xpath: '//version'

      
